#----------------------------------------------------------------
# Git Action - "Brain Games"
#
# Copyleft (c) by Andrey Bolgartsev 2021
#----------------------------------------------------------------
name: GitHub Actions BrainGames
on:
  push:
    branches:
      - main
jobs:
  Check and run:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - name: Install poetry and make lint
        run: |
          pip install poetry
          make install
          make lint